name: Docker Image CI

on:
  push:
    branches: [main]
    tags:
      - 'v*.*.*'
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU (for arm64)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Prepare image name (lowercase owner)
        id: prep
        shell: bash
        run: |
          OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}
          echo "image=${OWNER_LC}/lunatv" >> $GITHUB_OUTPUT
          echo "owner=${OWNER_LC}" >> $GITHUB_OUTPUT

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Read version from VERSION.txt
        id: ver
        shell: bash
        run: |
          VERSION=$(cat VERSION.txt | tr -d '\r\n')
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ steps.prep.outputs.image }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=ref,event=tag
            type=sha
            type=raw,value=v${{ steps.ver.outputs.version }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
